strictness: medium
doc-warnings: true
test-warnings: false
max-line-length: 120
ignore-patterns:
  - docs
  - docs_theme
  - backrefs(\\|/)uniprops\.py
dodgy:
  run: false
pep257:
  disable:
    - D202
pylint:
  disable:
    - import-error
